[package]
name = "momand"
version = "0.1.0"
description = "Monitor manager daemon"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
kdl = "6.5.0"
wayland-client = "0.31.11"
